version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-checks:
        - commentedOutCode
        - nilValReturn
        - sloppyReassign
        - weakCond
        - octalLiteral
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - rangeExprCopy
        - rangeValCopy
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - typeUnparen
        - unnamedResult
        - unnecessaryBlock
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    revive:
      confidence: 0.01
      rules:
        - name: duplicated-imports
          severity: error
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocritic
          - golint
        path: fake_.*\.go
      - linters:
          - dupl
          - errcheck
          - goconst
          - gocritic
          - golint
          - staticcheck
        path: examples/*
    paths:
      - (^|/)vendor($|/)
      - (^|/)testdata($|/)
      - (^|/)Godeps($|/)
      - (^|/)builtin($|/)
      - .*.gvm/.*
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - (^|/)vendor($|/)
      - (^|/)testdata($|/)
      - (^|/)Godeps($|/)
      - (^|/)builtin($|/)
      - .*.gvm/.*
